/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as LoginRouteImport } from './routes/login';
import { Route as IndexRouteImport } from './routes/index';
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index';
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any);
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute;
  '/opportunities/': typeof OpportunitiesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute;
  '/opportunities': typeof OpportunitiesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute;
  '/opportunities/': typeof OpportunitiesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/opportunities/$opportunityId'
    | '/opportunities/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/opportunities/$opportunityId'
    | '/opportunities';
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/opportunities/$opportunityId'
    | '/opportunities/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  SignupRoute: typeof SignupRoute;
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute;
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/opportunities/': {
      id: '/opportunities/';
      path: '/opportunities';
      fullPath: '/opportunities/';
      preLoaderRoute: typeof OpportunitiesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId';
      path: '/opportunities/$opportunityId';
      fullPath: '/opportunities/$opportunityId';
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
