/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as AuthedRouteImport } from './routes/_authed';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings';
import { Route as AuthedOpportunitiesIndexRouteImport } from './routes/_authed/opportunities.index';
import { Route as AuthedOpportunitiesOpportunityIdRouteImport } from './routes/_authed/opportunities.$opportunityId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedOpportunitiesIndexRoute =
  AuthedOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedOpportunitiesOpportunityIdRoute =
  AuthedOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => AuthedRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/settings': typeof AuthedSettingsRoute;
  '/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/opportunities/': typeof AuthedOpportunitiesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/settings': typeof AuthedSettingsRoute;
  '/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/opportunities': typeof AuthedOpportunitiesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authed': typeof AuthedRouteWithChildren;
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/_authed/settings': typeof AuthedSettingsRoute;
  '/_authed/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/_authed/opportunities/': typeof AuthedOpportunitiesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/opportunities/$opportunityId'
    | '/opportunities/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/opportunities/$opportunityId'
    | '/opportunities';
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authed/settings'
    | '/_authed/opportunities/$opportunityId'
    | '/_authed/opportunities/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  CheckoutRoute: typeof CheckoutRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/checkout': {
      id: '/checkout';
      path: '/checkout';
      fullPath: '/checkout';
      preLoaderRoute: typeof CheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed': {
      id: '/_authed';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed/settings': {
      id: '/_authed/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthedSettingsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/opportunities/': {
      id: '/_authed/opportunities/';
      path: '/opportunities';
      fullPath: '/opportunities/';
      preLoaderRoute: typeof AuthedOpportunitiesIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/opportunities/$opportunityId': {
      id: '/_authed/opportunities/$opportunityId';
      path: '/opportunities/$opportunityId';
      fullPath: '/opportunities/$opportunityId';
      preLoaderRoute: typeof AuthedOpportunitiesOpportunityIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute;
  AuthedOpportunitiesOpportunityIdRoute: typeof AuthedOpportunitiesOpportunityIdRoute;
  AuthedOpportunitiesIndexRoute: typeof AuthedOpportunitiesIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedOpportunitiesOpportunityIdRoute: AuthedOpportunitiesOpportunityIdRoute,
  AuthedOpportunitiesIndexRoute: AuthedOpportunitiesIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
