/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as AuthedRouteImport } from './routes/_authed';
import { Route as AuthedIndexRouteImport } from './routes/_authed/index';
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings';
import { Route as AuthedBuyersIndexRouteImport } from './routes/_authed/buyers.index';
import { Route as AuthedOpportunitiesOpportunityIdRouteImport } from './routes/_authed/opportunities.$opportunityId';
import { Route as AuthedBuyersNewRouteImport } from './routes/_authed/buyers.new';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedBuyersIndexRoute = AuthedBuyersIndexRouteImport.update({
  id: '/buyers/',
  path: '/buyers/',
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedOpportunitiesOpportunityIdRoute =
  AuthedOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedBuyersNewRoute = AuthedBuyersNewRouteImport.update({
  id: '/buyers/new',
  path: '/buyers/new',
  getParentRoute: () => AuthedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute;
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/settings': typeof AuthedSettingsRoute;
  '/buyers/new': typeof AuthedBuyersNewRoute;
  '/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/buyers/': typeof AuthedBuyersIndexRoute;
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/settings': typeof AuthedSettingsRoute;
  '/': typeof AuthedIndexRoute;
  '/buyers/new': typeof AuthedBuyersNewRoute;
  '/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/buyers': typeof AuthedBuyersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authed': typeof AuthedRouteWithChildren;
  '/checkout': typeof CheckoutRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/signup': typeof SignupRoute;
  '/_authed/settings': typeof AuthedSettingsRoute;
  '/_authed/': typeof AuthedIndexRoute;
  '/_authed/buyers/new': typeof AuthedBuyersNewRoute;
  '/_authed/opportunities/$opportunityId': typeof AuthedOpportunitiesOpportunityIdRoute;
  '/_authed/buyers/': typeof AuthedBuyersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/buyers/new'
    | '/opportunities/$opportunityId'
    | '/buyers/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/settings'
    | '/'
    | '/buyers/new'
    | '/opportunities/$opportunityId'
    | '/buyers';
  id:
    | '__root__'
    | '/_authed'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/buyers/new'
    | '/_authed/opportunities/$opportunityId'
    | '/_authed/buyers/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren;
  CheckoutRoute: typeof CheckoutRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/checkout': {
      id: '/checkout';
      path: '/checkout';
      fullPath: '/checkout';
      preLoaderRoute: typeof CheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed': {
      id: '/_authed';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed/': {
      id: '/_authed/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthedIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/settings': {
      id: '/_authed/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthedSettingsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/buyers/': {
      id: '/_authed/buyers/';
      path: '/buyers';
      fullPath: '/buyers/';
      preLoaderRoute: typeof AuthedBuyersIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/opportunities/$opportunityId': {
      id: '/_authed/opportunities/$opportunityId';
      path: '/opportunities/$opportunityId';
      fullPath: '/opportunities/$opportunityId';
      preLoaderRoute: typeof AuthedOpportunitiesOpportunityIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/buyers/new': {
      id: '/_authed/buyers/new';
      path: '/buyers/new';
      fullPath: '/buyers/new';
      preLoaderRoute: typeof AuthedBuyersNewRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRoute;
  AuthedIndexRoute: typeof AuthedIndexRoute;
  AuthedBuyersNewRoute: typeof AuthedBuyersNewRoute;
  AuthedOpportunitiesOpportunityIdRoute: typeof AuthedOpportunitiesOpportunityIdRoute;
  AuthedBuyersIndexRoute: typeof AuthedBuyersIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBuyersNewRoute: AuthedBuyersNewRoute,
  AuthedOpportunitiesOpportunityIdRoute: AuthedOpportunitiesOpportunityIdRoute,
  AuthedBuyersIndexRoute: AuthedBuyersIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
