import { computeProvisionalReadiness } from '../mock/fake-diagnosis';
import type { MockBuyer, MockDiagnosis, MockOpportunity } from '../mock/types';

// Per-opportunity export helpers (M17, PG-226). The export model is note-based:
// a single human-readable note, not structured fields. Two tiers — an
// opportunity with a CRM Record ID can produce a note-import file the CRM
// ingests directly; without one it is copy-only.

const titleCase = (value: string): string => {
  const humanized = value.replace(/_/g, ' ');
  return humanized.charAt(0).toUpperCase() + humanized.slice(1);
};

const ALIGNMENT_LABELS: Record<string, string> = {
  over_projecting: 'Over-projecting',
  under_projecting: 'Under-projecting',
  aligned: 'Aligned',
};

// Build the human-readable CRM note for one opportunity. Works with or without a
// diagnosis — an activity-less deal exports its provisional, CRM-stage-derived
// readiness, clearly labelled. The follow-up email is deliberately NOT included
// here; it is a separate, separately-copyable artifact in the Export tab.
export function buildCrmNote(args: {
  opportunity: MockOpportunity;
  buyer: MockBuyer | null;
  diagnosis: MockDiagnosis | null;
}): string {
  const { opportunity, buyer, diagnosis } = args;
  const lines: string[] = [];

  lines.push('PITCH GENIUS — BUYER READINESS NOTE');
  lines.push('===================================');
  lines.push(`Opportunity: ${opportunity.opportunityName}`);
  if (buyer) {
    const fullName = [buyer.firstName, buyer.lastName].filter(Boolean).join(' ');
    lines.push(`Buyer: ${fullName} · ${buyer.company}${buyer.title ? ` (${buyer.title})` : ''}`);
  }
  lines.push(`CRM stage: ${opportunity.currentCrmStage}`);
  if (opportunity.opportunityValue != null) {
    lines.push(`Value: $${opportunity.opportunityValue.toLocaleString()}`);
  }
  if (opportunity.expectedCloseDate) {
    lines.push(`Expected close: ${opportunity.expectedCloseDate}`);
  }

  lines.push('');
  lines.push('READINESS');
  if (diagnosis) {
    lines.push(
      `Buyer readiness: ${titleCase(diagnosis.readinessState)} — ${diagnosis.readinessScore}/100 (${diagnosis.confidenceLevel} confidence)`,
    );
    lines.push(
      `Pipeline alignment: ${ALIGNMENT_LABELS[diagnosis.alignmentOutcome] ?? titleCase(diagnosis.alignmentOutcome)}${diagnosis.alignmentLevel !== 'none' ? ` · ${diagnosis.alignmentLevel}` : ''}`,
    );
    lines.push(`  ${diagnosis.alignmentReason}`);
    if (diagnosis.primaryBlocker) {
      lines.push('');
      lines.push(`Primary blocker: ${diagnosis.primaryBlocker}`);
    }
    if (diagnosis.secondaryBlocker) {
      lines.push(`Secondary blocker: ${diagnosis.secondaryBlocker}`);
    }
    lines.push('');
    lines.push(`Recommended next action: ${diagnosis.diagnosis.recommended_next_action}`);
  } else {
    const provisional = computeProvisionalReadiness(opportunity.currentCrmStage);
    lines.push(
      `Buyer readiness: ${titleCase(provisional.state)} — ${provisional.score}/100 (provisional · no activity logged yet)`,
    );
    lines.push(
      'Pipeline alignment: not yet assessed — add buyer activity to check this deal against its CRM stage.',
    );
  }

  lines.push('');
  lines.push('—');
  lines.push(`Generated by Pitch Genius · ${new Date().toISOString().slice(0, 10)}`);

  return lines.join('\n');
}

// The two export tiers, keyed on whether the opportunity carries a CRM Record ID.
export type ExportTier = 'crm_import' | 'copy_only';

export function exportTier(opportunity: MockOpportunity): ExportTier {
  return opportunity.crmRecordId ? 'crm_import' : 'copy_only';
}

// Build the CRM note-import file — a two-column CSV (Record ID + Note) the CRM
// can ingest to attach the note to the matching record. Only valid for the
// `crm_import` tier; the caller gates on a non-null crmRecordId.
export function buildCrmNoteImportFile(args: {
  opportunity: MockOpportunity;
  note: string;
}): string {
  const recordId = args.opportunity.crmRecordId ?? '';
  const headers = ['Record ID', 'Note'];
  const row = [recordId, args.note];
  return [headers.map(csvEscape).join(','), row.map(csvEscape).join(',')].join('\n');
}

function csvEscape(value: string | number): string {
  const s = String(value);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

// Trigger a browser download for the given text payload.
export function downloadTextFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function safeFilenameSlug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}
